server {
    listen 80;
    root /usr/share/nginx/html;
    absolute_redirect off;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache";
    }

    error_page 404 /404.html;
}
